sudo: false
language: cpp
os:
  - linux
compiler:
  - gcc
branches:
  only:
  - master
env:
  global:
    - CURPATH=$(pwd)
    - ACEDIR=$HOME/Tools
    - ACE_ROOT=$ACEDIR/ACE_wrappers
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$LD_LIBRARY_PATH
    - COMPILER=g++-7
    - LANG="en_US.UTF-8"

before_install:
  - mkdir -p $ACEDIR
  - cd $ACEDIR
  - wget http://download.dre.vanderbilt.edu/previous_versions/ACE-6.4.0.tar.gz
  - tar zxf ACE-6.4.0.tar.gz
  

before_script:
  - export
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      echo -e "#include \"ace/config-linux.h\"" >> $ACE_ROOT/ace/config.h; 
      echo -e "#define ACE_HAS_EVENT_POLL" >> $ACE_ROOT/ace/config.h; 
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CXX" == "g++" ]; then
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      else
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      fi
    fi

  - cd $ACE_ROOT
  - $ACE_ROOT/bin/mwc.pl -type gnuace ACE.mwc
  - make ACE > /dev/null 2>&1
  - ls $ACE_ROOT/lib/
#
# Build Matrix
#
matrix:
  include:
  #
  # Build and sonarcloud
  #  
  - os: linux
    script: 
        - export    
        # - wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python
        # - sudo easy_install gcovr
        # install cppunit
        #- wget https://nchc.dl.sourceforge.net/project/cppunit/cppunit/1.12.1/cppunit-1.12.1.tar.gz
        - wget https://dev-www.libreoffice.org/src/cppunit-1.14.0.tar.gz
        - tar zxvf cppunit-1.14.0.tar.gz
        - cd cppunit-1.14.0
        - ./configure LDFLAGS='-ldl' --enable-std-cpp11 --prefix=$TRAVIS_BUILD_DIR
        - make 
        - make install
        - LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
        - cd $TRAVIS_BUILD_DIR/Build/Linux/
        - cd ../../lib
        - ls
        - cd $TRAVIS_BUILD_DIR/Build/Linux/
        - $ACE_ROOT/bin/mwc.pl -type gnuace psssonar.mwc
        - build-wrapper-linux-x86-64 --out-dir bw-output make -j 4
        - cd $TRAVIS_BUILD_DIR/purenessscopeserver/PacketParse_Interface
        - $ACE_ROOT/bin/mwc.pl -type gnuace
        - make -j 4
        # make PlugIn
        - cd $TRAVIS_BUILD_DIR/purenessscopeserver/example-Module/TcpTest
        - $ACE_ROOT/bin/mwc.pl -type gnuace
        - make -j 4    
        # Execute some tests
        - cd $TRAVIS_BUILD_DIR/Build/Linux/
        - nohup ./PurenessScopeServer > pssout.file 2>&1 &
        - sleep 20
        - cd $TRAVIS_BUILD_DIR/CppUnitTest/Test
        - make -j 4
        - ./Test_Pss
        #- cd $TRAVIS_BUILD_DIR/purenessscopeserver/FrameCore/Linux_Bin
        #- tail -f -n 10 pssout.file
        #close server
        - sleep 5
        - cd $TRAVIS_BUILD_DIR/Build/Linux
        - killall PurenessScopeServer
        - sleep 30
        - tail -n 100 pssout.file        
        - cd $TRAVIS_BUILD_DIR/Build/Linux/.obj
        - ls *.gcda
        - cd $TRAVIS_BUILD_DIR/Build/Linux/
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/Common/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/Console/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/FileTest/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/Encrypt/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/PacketParse/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/LogSystem/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/Message/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/Reactor/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/UDP/*.cpp > /dev/null
        - gcov -r -o ./.obj ../../purenessscopeserver/FrameCore/CppUnit/*.cpp > /dev/null
        - ls
        - cd $TRAVIS_BUILD_DIR/Build/Linux/reports/cppunit
        #- ls 
        - cat report.xml
        - cd $TRAVIS_BUILD_DIR/purenessscopeserver/FrameCore
        - sonar-scanner -X

    addons:
      sonarcloud:
        organization: "freeeyes-github"
        token:
          secure: "qzWDGQvGlJlBvJyG+jhAQXRU3K6n0tf+u6goSNMnW9K1/qkJLThO158V8o4N/Yu4JE5L7hIVlSUUuJbU6xEWWazm4x4rI4KGQ8z8K6F7Jm7kshpNybp8PzibkOiB7K2F8+adrk9bELeYGSA06UqlAtvSn5Q22GlFq+Zwlp8RYGFcZHNOaK0GGPPRu4xHdDMIBhpg5kwjEEpYbfWYmhJJRqNzkityhBxylvcCCnln6FDUpgRbIdCzntl2f5Ctp8ZA9zS5ZX/XMOIbtEePT8DisBQ6s0wMIjthBgEhI9om8yphNe8QYv8Y9kfcK+dvpOvm9RKXZrmzXBKgl2JEmp9vxYFLspQy0y4oVeM7l+7gPa6Bj3lpszbOhZZtHmoBQh7RETW5Fmg3ubKDi9+vGWx417k/JRjdGD8NHHDPDhcDSWCgx85y2UcpO1JUY1LoLl7pF6HAQkFG+Eb3wO7bogvgTd46QJixrmJu/kCC7bFVhKVGGpgRq1A4h4dkwfDvTw8w5zL74zd7AdghwfqihEq2PwfizADCoaszocgOg4kmqIsakuVaGE7r4fo4E4sShcb036OIQz2F6gJmLMgasTMG5E1s+K/j2m3QOZ2fLIyKm2/0rKbL9jYvtYf27FWpBKyPnyIKNegZSu7F/RDEGk2qMkIeK7iuV/4DsDXgJcXMiHk="
          
    cache:
      directories:
        - '$HOME/.sonar/cache'          
          
  #
  # Update Report
  #
  - os: linux
    env:
      - GH_REF: github.com/freeeyes/PSS.git
      - secure: "Tqz9j2VlU+mJgCcnceaam/X/N8cgQa+O92qeGUFOKGAqJkxiKHQAPnqj7+YmgCAKVEbBEMPo08Putcro00YQKElkrWpuUc2J49+DYzd8ZoSXgUEOPuYwTzPSIcSCN1cKogjBuTxJrp5WbmRAiH6gIhB+m4r2ToCGnZ6MXnkVGracjRaPoqLC4j3S5FXuq/Ilp2ZW9SqRQiy+yGQzW7UvbyE0LRhoXb/ptFFMgW/NomoUlOIyCFSqXfPMxQsHFGD4ifcjl8pGWGE5OB0Sm9IMbe9/DOL11ouSPy/0OevPH23VuYmiIz+acVa7A48Dm1Z5sFsHvyFAiU5tiXCVS7VTCqxL4M4Ac1NlpDDMngwkms0w4M9J9TXNzNA958glhfBoMaIWcHMpZ0hEdWrulAKIrBZnevm0yMvTfnxmyA4Pie98UFrAlljZXiUTZtrHGC2Z1oSJZ92sOfc5uDyA1lZMf7XiLN9HbCHBZtKdo5PS2PhF97oOTZdOvpRKkwgMb+sqfVM/JGsdsS8eSmkIyCB0JkDjJKWuA7q8f3xDlPyigjUtFXkllEa8eyYsRFdoLYIK/vLWo+/J7PoICxCdXUnC3YmcXkGaisQxnjgAyhnEnG8z38Ra2uDh2W7ltLfgEtaAChYp6UZMR4XboM7F1DzB2zFSociUJ61tn4fibIzPGOg="
    script:
      - export
      - cd $TRAVIS_BUILD_DIR/purenessscopeserver/PacketParse_Interface
      - $ACE_ROOT/bin/mwc.pl -type gnuace
      - make -j 4
      # make PlugIn
      - cd $TRAVIS_BUILD_DIR/purenessscopeserver/example-Module/TcpTest
      - $ACE_ROOT/bin/mwc.pl -type gnuace
      - make -j 4
      - cd $TRAVIS_BUILD_DIR/Build/Linux/
      - $ACE_ROOT/bin/mwc.pl -type gnuace pss.mwc
      - ls
      - make -j 4
      - nohup ./PurenessScopeServer > pssout.file 2>&1 &
      - sleep 10
      - cd $TRAVIS_BUILD_DIR/CppUnitTest/Test
      - make -j 4
      - ./Test_Pss
      # - cd $TRAVIS_BUILD_DIR/Build/Linux/
      # - tail -f -n 10 pssout.file
      - killall -9 PurenessScopeServer  
      #- cd $TRAVIS_BUILD_DIR/Build/Linux/
      #- cat pssout.file
      
      - cd $TRAVIS_BUILD_DIR
      - git init
      - git config user.name "freeeyes"
      - git config user.email "freeeyes@163.com"
      - git add -u ./testresult/result.md
      - git commit -m "[ci skip]Travis CI Update result.md"
      - git push -f "https://${GH_TOKEN}@${GH_REF}" HEAD:master
